# Generated by Django 3.2.5 on 2021-08-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmao', models.CharField(max_length=20)),
            ],
        ),
    ]
